### ISSUE TITLE
To-do list of responsive elements

### ISSUE THREAD

**Issue by kimkvn** [kimkvn/TIYsurfpaddle#2]
- [x] Header
  - [x] @min width 600px
    - [x] Tsunami logo goes to upper left corner, 
      - [x] "Surf & Paddle Blog" appears next to it
    - [x] "About" and "Search" move to upper right corner
  - [x] @min width 800px
    - [x] h1 "Surf & Paddle Co." gets bigger
- [x] Article
  - [x] @min width 600px
    - [x] "Some Author" block disappears, instead small some author under title next to date
    - [x] Social links disappear
  - [x] @min width 800px
    - [x] Sidebar Section Heading appears next to Ad image and link. Text in sidebar wraps around Ad.
  - [x] @min width 1024px
    - [x] Some Author, Ad, and Sidebar all appear on right side of page

**Comment by kimkvn** [comment]
DONE.
